language: R
cache: packages

jobs:
  include:
  - r: 3.0
  warnings_are_errors: false
  - r: 3.1
  warnings_are_errors: false
  - r: 3.2
  warnings_are_errors: false
  - r: 3.3
  warnings_are_errors: false
  - r: 3.4
  warnings_are_errors: false
  - r: 3.5
  warnings_are_errors: false
  - r: release
  warnings_are_errors: false
  - r: devel
  warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'