# Travis configuration guide for R language:
#   https://docs.travis-ci.com/user/languages/r/
#   https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: R
cache: packages

jobs:
  include:
  - r: 3.3
#    warnings_are_errors: false
- r: 3.4
#    warnings_are_errors: false
- r: release
#    warnings_are_errors: false
- r: devel
#    warnings_are_errors: false


after_success:
  - Rscript -e 'covr::codecov()'